FROM sjoeboo/sensu:base

ENV SENSU_TYPE client

ENV SENSU_PLUGINS "sensu-plugins-network-checks sensu-plugins-disk-checks sensu-plugins-http sensu-plugins-memory-checks sensu-plugins-sensu sensu-plugins-dns sensu-plugins-cpu-checks sensu-plugins-process-checks sensu-plugins-docker sensu-plugins-load-checks"
